-- users
INSERT INTO users (username, password, email, score, country)
VALUES ('Melika', 'pass123@', 'melika@example.com', 0, 'Iran'),
       ('Moeein', 'pass123@', 'moeein@example.com', 0, 'Iran');
--quiz
INSERT INTO quiz (question, option1, option2, option3, option4, correct_answer)
VALUES 
('In what year did the Great October Socialist Revolution take place?',
 '1917',
 '1923',
 '1914',
 '1920',
 1),
('What is the largest lake in the world?',
 'Caspian Sea',
 'Baikal',
 'Lake Superior',
 'Ontario',
 2),
('Which planet in the solar system is known as the “Red Planet”?',
 'Venus',
 'Earth',
 'Mars',
 'Jupiter',
 3),
('Who wrote the novel “War and Peace”?',
 'Anton Chekhov',
 'Fyodor Dostoevsky',
 'Leo Tolstoy',
 'Ivan Turgenev',
 3),
('What is the capital of Japan?',
 'Beijing',
 'Tokyo',
 'Seoul',
 'Bangkok',
 2),
('Which river is the longest in the world?',
 'Amazon',
 'Mississippi',
 'Nile',
 'Yangtze',
 3),
('What gas is used to extinguish fires?',
 'Oxygen',
 'Nitrogen',
 'Carbon dioxide',
 'Hydrogen',
 2),
('What animal is the national symbol of Australia?',
 'Kangaroo',
 'Koala',
 'Emu',
 'Crocodile',
 1),
('Which of the following planets is not a gas giant?',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 1),
('What is the name of the process by which plants convert sunlight into energy?',
 'Respiration',
 'Photosynthesis',
 'Oxidation',
 'Evolution',
 2),
('What chemical element is designated as “Hg”?',
 'Silver',
 'Tin',
 'Copper',
 'Mercury',
 4),
('In what year was the first international modern Olympiad held?',
 '1896',
 '1900',
 '1912',
 '1924',
 1),
('For which of these disciplines Nobel Prize is awarded?',
 'Physics, Chemistry',
 'Physiology',
 'Medicine',
 'All of the above',
 4),
('Entomology is the science that studies:',
 'Behavior of human beings',
 'Insects',
 'The origin and history of technical and scientific terms',
 'The formation of rocks',
 2),
('Hitler's party is known as:',
 'Labour Party',
 'Nazi Party',
 'Ku-Klux-Klan',
 'Democratic Party',
 2),
('For which Galileo is famous?',
 'Developed the telescope',
 'Discovered four satellites of Jupiter',
 'Found that the swinging motion of the pendulum results in consistent time measurement.',
 'All of the above',
 4),
('When the First Afghan War took place in',
 '1839',
 '1843',
 '1833',
 '1848',
 1),
('Ecology deals with',
 'Birds',
 'Cell formation',
 'Relation between organisms and their environment',
 'Tissues',
 3),
('Which is the largest island?',
 'New Guinea',
 'Andaman Nicobar',
 'Greenland',
 'Hawaii',
 3),
('Which one is the hottest continent?',
 'Africa',
 'South Asia',
 'North America',
 'Australia',
 1),
('What do Koalas usually eat?',
 'Bamboo',
 'Eucalyptus',
 'Aloe Vera',
 'Banana',
 2),
('What is the most popular bread in France?',
 'Brioche',
 'Baguette',
 'White bread',
 'Ciabatta',
 2),
('What is the official currency of Japan?',
 'Won',
 'Yuan',
 'Yen',
 'Dollars',
 3),
('What is the phobia of thunder and rain?',
 'Agoraphobia',
 'Ombrophobia',
 'Acrophobia',
 'Claustrophobia',
 2),
('What does Carpe Diem mean in Latin?',
 'Enjoy the moment',
 'Have no fear',
 'Sorry I blew it',
 'Hello',
 1),
('Which one of the following countries is not in Africa?',
 'Morocco',
 'Yemen',
 'Sudan',
 'Algeria',
 2),
('What is considered the lung of the Earth?',
 'Amazon rainforest',
 'The Mississippi River',
 'The Sahara',
 'Everest',
 1),
('Where does the Sushi come from?',
 'Japan',
 'China',
 'America',
 'South Korea',
 1),
('In which century the Mona Lisa was painted?',
 '18th century',
 '15th century',
 '16th century',
 '14th century',
 3),
('Who wrote the “Great Gatsby” novel?',
 'Leo Tolstoy',
 'Hemingway',
 'Stephen King',
 'F. Scott Fitzgerald',
 4),
('Which is the richest country in the world?',
 'Qatar',
 'Russia',
 'The USA',
 'The UAE',
 1),
('Which county is the biggest grower of coffee?',
 'Spain',
 'India',
 'Ethiopia',
 'Brazil',
 4),
('How many bones are in the body of an adult human?',
 '330',
 '206',
 '250',
 '210',
 2),
('When the humans use more facial muscles?',
 'While smiling',
 'While frowning',
 'While sleeping',
 'While talking',
 2),
('Who wrote “Crime and Punishment”?',
 'Leo Tolstoy',
 'Fyodor Dostoevsky',
 'Anton Chekhov',
 'Ivan Turgenev',
 2),
('In what year was the United Nations (UN) founded?',
 '1945',
 '1919',
 '1956',
 '1961',
 1),
('Which city is called the “City of Winds”?',
 'Chicago',
 'Seattle',
 'Washington',
 'Veliky Novgorod',
 1),
('What animal is a symbol of peace and neutrality?',
 'Polar bear',
 'White tiger',
 'White lion',
 'White crane',
 4),
('What element is the main constituent of diamonds?',
 'Carbon',
 'Oxygen',
 'Silver',
 'Gold',
 1),
('40.In what year was Ferdinand Magellan's first successful circumnavigation of the world?',
 '1492',
 '1520',
 '1588',
 '1620',
 2),
('Which river is the second longest in the world?',
 'Amazon',
 'Yangtze',
 'Nile',
 'Mississippi',
 2),
('What year was the first man sent to space?',
 '1957',
 '1961',
 '1969',
 '1975',
 2),
('Which sea is considered the most salty on Earth?',
 'Red Sea',
 'Mediterranean Sea',
 'Dead Sea',
 'Black Sea',
 3),
('Which organ in the human body is responsible for the secretion of bile?',
 'Liver',
 'Kidneys',
 'Spleen',
 'Stomach',
 1),
('Which planet in the solar system is known as the “Morning Star” or “Evening Star”?',
 'Mars',
 'Venus',
 'Mercury',
 'Jupiter',
 2),
('What chemical element is designated as “Cu”?',
 'Zinc',
 'Copper',
 'Cobalt',
 'Kurtz',
 2),
('In what year did the French Revolution take place?',
 '1789',
 '1812',
 '1905',
 '1793',
 1),
('What ocean is between Africa and Australia?',
 'Pacific',
 'Indian',
 'Atlantic',
 'Arctic',
 2),
('Which chemical element makes up most of the atmosphere of Mars?',
 'Carbon dioxide',
 'Oxygen',
 'Nitrogen',
 'Hydrogen',
 1),
('What chemical element makes up most of the atmosphere of Titan?',
 'Methane',
 'Carbon dioxide',
 'Hydrogen',
 'Oxygen',
 1),
('In what year did the discovery of Antarctica occur?',
 '1500',
 '1778',
 '1820',
 '1892',
 3),
('In what year was the International Red Cross and Red Guard Organization (Red Cross) founded?',
 '1863',
 '1901',
 '1945',
 '1980',
 1),
('What instrument is depicted in Leonardo da Vinci's famous painting “The Last Supper”?',
 'Tablets',
 'Lute',
 'Guitar',
 'Harp',
 2),
('In which country did the Chernobyl nuclear disaster take place?',
 'Russia',
 'Ukraine',
 'Belarus',
 'Lithuania',
 2),
('What ocean lies between North America and Eurasia?',
 'Quiet',
 'Atlantic',
 'Indian',
 'Arctic',
 2),
('In what year was the manga Karta signed?',
 '1066',
 '1215',
 '1492',
 '1689',
 2),
('What chemical element is used to cool and freeze food?',
 'Sodium',
 'Hydrogen',
 'Oxygen',
 'Nitrogen',
 4),
('Which country is famous for its pyramids and the Sphinx?',
 'India',
 'China',
 'Mexico',
 'Egypt',
 4),
('What is the name of the science that studies the past of life on Earth?',
 'Palaeontology',
 'Astronomy',
 'Anthropology',
 'Geology',
 1),
('What chemical element forms the basis of the haemoglobin molecule responsible for the transport of oxygen in the blood?',
 'Nitrogen',
 'Iron',
 'Oxygen',
 'Silver',
 2),
('In what year was the League of Nations founded?',
 '1919',
 '1923',
 '1939',
 '1945',
 1),
('Which planet in the solar system has the most diverse climate and atmosphere?',
 'Mercury',
 'Earth',
 'Mars',
 'Venus',
 2),
('In what year did the Berlin Wall fall?',
 '1961',
 '1989',
 '1991',
 '2000',
 2),
('Which sea lies between Asia and Africa?',
 'Caspian',
 'Red',
 'Mediterranean',
 'Dead',
 3),
('Which organ in the human body is responsible for secreting insulin?',
 'Liver',
 'Kidneys',
 'Pancreas',
 'Stomach',
 3),
('What year did the Great Depression start?',
 '1914',
 '1929',
 '1939',
 '1945',
 2),
('What chemical element is used in the manufacture of glass?',
 'Silver',
 'Sodium',
 'Silicone',
 'Oxygen',
 3),
('Which instrument is depicted in Edvard Munch's famous painting “The Scream”?',
 'Flute',
 'Cello',
 'Clarinet',
 'Pictures',
 2),
('Which planet in the solar system is known as the “Planet of Love”?',
 'Venus',
 'Mars',
 'Earth',
 'Jupiter',
 1),
('What chemical element is the main component of carbon dioxide (CO2)?',
 'Oxygen',
 'Hydrogen',
 'Carbon',
 'Nitrogen',
 3),
('In what year was UNESCO (United Nations Educational, Scientific and Cultural Organization) founded?',
 '1942',
 '1950',
 '1965',
 '1973',
 2),
('What chemical element is used in the production of steel products?',
 'Copper',
 'Iron',
 'Tin',
 'Silver',
 2),
('What year was the Olympic Organization founded?',
 '1886',
 '1896',
 '1900',
 '1912',
 2),
('What chemical element is the main component of human bones and teeth?',
 'Calcium',
 'Iron',
 'Sodium',
 'Magnesium',
 1),
('Which organ in the human body is responsible for filtering blood and producing urine?',
 'Heart',
 'Liver',
 'Kidneys',
 'Spleen',
 3),
('In what year was the first official Olympics held in modern times?',
 '1892',
 '1900',
 '1924',
 '1936',
 2),
('Which planet in the solar system has the largest diameter?',
 'Mercury',
 'Venus',
 'Earth',
 'Jupiter',
 4),
('What chemical element is used to fill balloons and airships?',
 'Hydrogen',
 'Oxygen',
 'Helium',
 'Neon',
 3),
('In what year did the Renaissance (Renaissance) begin?',
 '1300',
 '1453',
 '1500',
 '1600',
 3),
('What chemical element is used in the manufacture of batteries?',
 'Lead',
 'Copper',
 'Aluminum',
 'Lithium',
 4),
('What type of radiation allows X-ray examinations?',
 'Ultrasound',
 'Radioactivity',
 'Infrared',
 'X-ray',
 4),
('What chemical element is used to create rainbows in televisions and computer monitors?',
 'Helium',
 'Oxygen',
 'Hydrogen',
 'Neon',
 4),
('Which planet in the solar system is known as the “Blue Planet”?',
 'Venus',
 'Earth',
 'Uranus',
 'Neptune',
 2),
('In what year did the first man land on the moon?',
 '1961',
 '1969',
 '1975',
 '1983',
 2),
('Which actor portrayed James Bond in a record seven movies?',
 'Bradd Pitt',
 'Daniel Craig',
 'Pierce Brosnan',
 'Roger Moore',
 4),
('Filaria is caused by',
 'Bacteria',
 'Mosquito',
 'Protozoa',
 'Virus',
 2),
('Fathometer is used to measure',
 'Earthquakes',
 'Rainfall',
 'Ocean depth',
 'Sound intensity',
 3),
('In which year, did terrorists crash two planes into New York's World Trade Centre?',
 '2000',
 '2001',
 '2002',
 '2003',
 2),
('In an adult human body, the total number of red blood cells is',
 '15 trillion',
 '20 trillion',
 '25 trillion',
 '30 trillion',
 4),
('In which season do we need more fat?',
 'Autumn',
 'Spring',
 'Winter',
 'Summer',
 3),
('How many teeth does an adult dog have?',
 '32',
 '34',
 '38',
 '42',
 4),
('How many times has Brazil won the World Cup?',
 '4',
 '2',
 '5',
 '1',
 3),
('How many players are there on each side of the Basketball game?',
 '4',
 '5',
 '6',
 '7',
 2),
('Hundred year war was between',
 'France and England',
 'Greek and Persian forces',
 'Civil War in England',
 'None of the above',
 1),
('Which animal is known to be the ‘Ship of the Desert”?',
 'Dog',
 'Camel',
 'Cat',
 'Snake',
 2),
('Who was the first person to walk on the moon?',
 'Yuri Gagarin',
 'Neil Armstrong',
 'John Glenn',
 'Buzz Aldrin',
 2),
('Which country was divided into two parts by the Wall?',
 'France',
 'Germany',
 'Austria',
 'Poland',
 2),
('Which city is the capital of Italy?',
 'Venice',
 'Florence',
 'Rome',
 'Milan',
 3),
('Which of these buildings is in India?',
 'Eiffel Tower',
 'Colosseum',
 'Taj Mahal',
 'Great Wall of China',
 3),
('In which country was the famous composer Wolfgang Amadeus Mozart born?',
 'Germany',
 'Austria',
 'Czech Republic',
 'Italy',
 2),
('Which of the following inventions is attributed to Thomas Edison?',
 'Bulb',
 'Telephone',
 'Computer',
 'Rocket',
 1),
('Which animal is a symbol of courage and bravery in Chinese culture?',
 'Leo',
 'Dragon',
 'Eagle',
 'Bear',
 2),
('Who invented the telegraph?',
 'Alexander Graham Bell',
 'Guglielmo Marconi',
 'Thomas Edison',
 'Samuel Morse',
 4),
('104.What animal is the symbol of China?',
 'Panda',
 'Elephant',
 'Tiger',
 'Leo',
 1),
('Which of these cities is located in Egypt?',
 'Athens',
 'Cairo',
 'Baghdad',
 'London',
 2),
('Which vitamin is often referred to as the “sunshine vitamin”?',
 'Vitamin A',
 'Vitamin B',
 'Vitamin C',
 'Vitamin D',
 4),
('What event led to the start of World War II?',
 'The fall of the Berlin Wall',
 'Attack on Pearl Harbor',
 'The signing of the Treaty of Versailles',
 'The capture of Crimea by Germany',
 2),
('What is the name of the longest river in Russia?',
 'Volga',
 'Lena',
 'Neva',
 'Amur',
 2),
('Who was the first President of the USA?',
 'George Washington',
 'John Adams',
 'Thomas Jefferson',
 'James Madison',
 1),
('Who is the founder of the modern theory of evolution?',
 'Charles Darwin',
 'Isaac Newton',
 'Albert Einstein',
 'Marie Curie',
 1),
('Which country is considered the birthplace of the Olympic Games?',
 'Greece',
 'Rome',
 'Egypt',
 'China',
 1),
('Who wrote the play “Romeo and Juliet”?',
 'William Shakespeare',
 'Alexander Pushkin',
 'Fyodor Dostoyevsky',
 'Victor Hugo',
 1),
('Which of these animals cannot jump?',
 'Cat',
 'Horse',
 'Snake',
 'Kangaroo',
 3),
('Which canal connects the Red and Mediterranean seas?',
 'Suez Canal',
 'Panama Canal',
 'Gotthard Tunnel',
 'Bosphorus Strait',
 1),
('What year did the Titanic sink in the Atlantic Ocean?',
 '1913',
 '1912',
 '1812',
 '1920',
 2),
('What social network used “stories” first?',
 'VKontakte',
 'Facebook',
 'Instagram',
 'Twitter',
 3),
('What game became popular due to the principle of “catch Pokemon in the real world”?',
 'Mario Kart Tour',
 'Clash of Clans',
 'Pokemon GO',
 'Candy Crush Saga',
 3),
('What device is used to view content in virtual reality?',
 'Smartphone',
 '3D glasses',
 'VR Headset',
 'Tablet',
 3),
('Which month is the shortest on the calendar?',
 'January',
 'February',
 'March',
 'December',
 1),
('Which city is the capital of Russia?',
 'St. Petersburg',
 'Kazan',
 'Sochi',
 'Moscow',
 4);