-- users
INSERT INTO users (username, password, email, score, country)
VALUES ('Melika', 'pass123@', 'melika@example.com', 0, 'Iran'),
       ('Moeein', 'pass123@', 'moeein@example.com', 0, 'Iran');

--teachers
INSERT INTO teacher (f_name, l_name, ph_number, price, score)
VALUES ('a', 'A', 09123456789, 4000000, 4.1),
       ('b', 'B', 09876543210, 2000000, 3.2);


--general questions
INSERT INTO general_qs(question, option1, option2, option3, option4, correct_answer)
VALUES ('In what year did the Great October Socialist Revolution take place?',
        '1917',
        '1923',
        '1914',
        '1920',
        1),
       ('What is the largest lake in the world?',
        'Caspian Sea',
        'Baikal',
        'Lake Superior',
        'Ontario',
        2),
       ('Which planet in the solar system is known as the “Red Planet”?',
        'Venus',
        'Earth',
        'Mars',
        'Jupiter',
        3),
       ('Who wrote the novel “War and Peace”?',
        'Anton Chekhov',
        'Fyodor Dostoevsky',
        'Leo Tolstoy',
        'Ivan Turgenev',
        3),
       ('What is the capital of Japan?',
        'Beijing',
        'Tokyo',
        'Seoul',
        'Bangkok',
        2),
       ('Which river is the longest in the world?',
        'Amazon',
        'Mississippi',
        'Nile',
        'Yangtze',
        3),
       ('What gas is used to extinguish fires?',
        'Oxygen',
        'Nitrogen',
        'Carbon dioxide',
        'Hydrogen',
        2),
       ('What animal is the national symbol of Australia?',
        'Kangaroo',
        'Koala',
        'Emu',
        'Crocodile',
        1),
       ('Which of the following planets is not a gas giant?',
        'Mars',
        'Jupiter',
        'Saturn',
        'Uranus',
        1),
       ('What is the name of the process by which plants convert sunlight into energy?',
        'Respiration',
        'Photosynthesis',
        'Oxidation',
        'Evolution',
        2),
       ('What chemical element is designated as “Hg”?',
        'Silver',
        'Tin',
        'Copper',
        'Mercury',
        4),
       ('In what year was the first international modern Olympiad held?',
        '1896',
        '1900',
        '1912',
        '1924',
        1),
       ('For which of these disciplines Nobel Prize is awarded?',
        'Physics, Chemistry',
        'Physiology',
        'Medicine',
        'All of the above',
        4),
       ('Entomology is the science that studies:',
        'Behavior of human beings',
        'Insects',
        'The origin and history of technical and scientific terms',
        'The formation of rocks',
        2),
       ('Hitler party is known as:',
        'Labour Party',
        'Nazi Party',
        'Ku-Klux-Klan',
        'Democratic Party',
        2),
       ('For which Galileo is famous?',
        'Developed the telescope',
        'Discovered four satellites of Jupiter',
        'Found that the swinging motion of the pendulum results in consistent time measurement.',
        'All of the above',
        4),
       ('When the First Afghan War took place in',
        '1839',
        '1843',
        '1833',
        '1848',
        1),
       ('Ecology deals with',
        'Birds',
        'Cell formation',
        'Relation between organisms and their environment',
        'Tissues',
        3),
       ('Which is the largest island?',
        'New Guinea',
        'Andaman Nicobar',
        'Greenland',
        'Hawaii',
        3),
       ('Which one is the hottest continent?',
        'Africa',
        'South Asia',
        'North America',
        'Australia',
        1),
       ('What do Koalas usually eat?',
        'Bamboo',
        'Eucalyptus',
        'Aloe Vera',
        'Banana',
        2),
       ('What is the most popular bread in France?',
        'Brioche',
        'Baguette',
        'White bread',
        'Ciabatta',
        2),
       ('What is the official currency of Japan?',
        'Won',
        'Yuan',
        'Yen',
        'Dollars',
        3),
       ('What is the phobia of thunder and rain?',
        'Agoraphobia',
        'Ombrophobia',
        'Acrophobia',
        'Claustrophobia',
        2),
       ('What does Carpe Diem mean in Latin?',
        'Enjoy the moment',
        'Have no fear',
        'Sorry I blew it',
        'Hello',
        1),
       ('Which one of the following countries is not in Africa?',
        'Morocco',
        'Yemen',
        'Sudan',
        'Algeria',
        2),
       ('What is considered the lung of the Earth?',
        'Amazon rainforest',
        'The Mississippi River',
        'The Sahara',
        'Everest',
        1),
       ('Where does the Sushi come from?',
        'Japan',
        'China',
        'America',
        'South Korea',
        1),
       ('In which century the Mona Lisa was painted?',
        '18th century',
        '15th century',
        '16th century',
        '14th century',
        3),
       ('Who wrote the “Great Gatsby” novel?',
        'Leo Tolstoy',
        'Hemingway',
        'Stephen King',
        'F. Scott Fitzgerald',
        4),
       ('Which is the richest country in the world?',
        'Qatar',
        'Russia',
        'The USA',
        'The UAE',
        1),
       ('Which county is the biggest grower of coffee?',
        'Spain',
        'India',
        'Ethiopia',
        'Brazil',
        4),
       ('How many bones are in the body of an adult human?',
        '330',
        '206',
        '250',
        '210',
        2),
       ('When the humans use more facial muscles?',
        'While smiling',
        'While frowning',
        'While sleeping',
        'While talking',
        2),
       ('Who wrote “Crime and Punishment”?',
        'Leo Tolstoy',
        'Fyodor Dostoevsky',
        'Anton Chekhov',
        'Ivan Turgenev',
        2),
       ('In what year was the United Nations (UN) founded?',
        '1945',
        '1919',
        '1956',
        '1961',
        1),
       ('Which city is called the “City of Winds”?',
        'Chicago',
        'Seattle',
        'Washington',
        'Veliky Novgorod',
        1),
       ('What animal is a symbol of peace and neutrality?',
        'Polar bear',
        'White tiger',
        'White lion',
        'White crane',
        4),
       ('What element is the main constituent of diamonds?',
        'Carbon',
        'Oxygen',
        'Silver',
        'Gold',
        1),
       ('40.In what year was Ferdinand Magellan first successful circumnavigation of the world?',
        '1492',
        '1520',
        '1588',
        '1620',
        2),
       ('Which river is the second longest in the world?',
        'Amazon',
        'Yangtze',
        'Nile',
        'Mississippi',
        2),
       ('What year was the first man sent to space?',
        '1957',
        '1961',
        '1969',
        '1975',
        2),
       ('Which sea is considered the most salty on Earth?',
        'Red Sea',
        'Mediterranean Sea',
        'Dead Sea',
        'Black Sea',
        3),
       ('Which organ in the human body is responsible for the secretion of bile?',
        'Liver',
        'Kidneys',
        'Spleen',
        'Stomach',
        1),
       ('Which planet in the solar system is known as the “Morning Star” or “Evening Star”?',
        'Mars',
        'Venus',
        'Mercury',
        'Jupiter',
        2),
       ('What chemical element is designated as “Cu”?',
        'Zinc',
        'Copper',
        'Cobalt',
        'Kurtz',
        2),
       ('In what year did the French Revolution take place?',
        '1789',
        '1812',
        '1905',
        '1793',
        1),
       ('What ocean is between Africa and Australia?',
        'Pacific',
        'Indian',
        'Atlantic',
        'Arctic',
        2),
       ('Which chemical element makes up most of the atmosphere of Mars?',
        'Carbon dioxide',
        'Oxygen',
        'Nitrogen',
        'Hydrogen',
        1),
       ('What chemical element makes up most of the atmosphere of Titan?',
        'Methane',
        'Carbon dioxide',
        'Hydrogen',
        'Oxygen',
        1),
       ('In what year did the discovery of Antarctica occur?',
        '1500',
        '1778',
        '1820',
        '1892',
        3),
       ('In what year was the International Red Cross and Red Guard Organization (Red Cross) founded?',
        '1863',
        '1901',
        '1945',
        '1980',
        1),
       ('What instrument is depicted in Leonardo da Vinci famous painting “The Last Supper”?',
        'Tablets',
        'Lute',
        'Guitar',
        'Harp',
        2),
       ('In which country did the Chernobyl nuclear disaster take place?',
        'Russia',
        'Ukraine',
        'Belarus',
        'Lithuania',
        2),
       ('What ocean lies between North America and Eurasia?',
        'Quiet',
        'Atlantic',
        'Indian',
        'Arctic',
        2),
       ('In what year was the manga Karta signed?',
        '1066',
        '1215',
        '1492',
        '1689',
        2),
       ('What chemical element is used to cool and freeze food?',
        'Sodium',
        'Hydrogen',
        'Oxygen',
        'Nitrogen',
        4),
       ('Which country is famous for its pyramids and the Sphinx?',
        'India',
        'China',
        'Mexico',
        'Egypt',
        4),
       ('What is the name of the science that studies the past of life on Earth?',
        'Palaeontology',
        'Astronomy',
        'Anthropology',
        'Geology',
        1),
       ('What chemical element forms the basis of the haemoglobin molecule responsible for the transport of oxygen in the blood?',
        'Nitrogen',
        'Iron',
        'Oxygen',
        'Silver',
        2),
       ('In what year was the League of Nations founded?',
        '1919',
        '1923',
        '1939',
        '1945',
        1),
       ('Which planet in the solar system has the most diverse climate and atmosphere?',
        'Mercury',
        'Earth',
        'Mars',
        'Venus',
        2),
       ('In what year did the Berlin Wall fall?',
        '1961',
        '1989',
        '1991',
        '2000',
        2),
       ('Which sea lies between Asia and Africa?',
        'Caspian',
        'Red',
        'Mediterranean',
        'Dead',
        3),
       ('Which organ in the human body is responsible for secreting insulin?',
        'Liver',
        'Kidneys',
        'Pancreas',
        'Stomach',
        3),
       ('What year did the Great Depression start?',
        '1914',
        '1929',
        '1939',
        '1945',
        2),
       ('What chemical element is used in the manufacture of glass?',
        'Silver',
        'Sodium',
        'Silicone',
        'Oxygen',
        3),
       ('Which instrument is depicted in Edvard Munch famous painting “The Scream”?',
        'Flute',
        'Cello',
        'Clarinet',
        'Pictures',
        2),
       ('Which planet in the solar system is known as the “Planet of Love”?',
        'Venus',
        'Mars',
        'Earth',
        'Jupiter',
        1),
       ('What chemical element is the main component of carbon dioxide (CO2)?',
        'Oxygen',
        'Hydrogen',
        'Carbon',
        'Nitrogen',
        3),
       ('In what year was UNESCO (United Nations Educational, Scientific and Cultural Organization) founded?',
        '1942',
        '1950',
        '1965',
        '1973',
        2),
       ('What chemical element is used in the production of steel products?',
        'Copper',
        'Iron',
        'Tin',
        'Silver',
        2),
       ('What year was the Olympic Organization founded?',
        '1886',
        '1896',
        '1900',
        '1912',
        2),
       ('What chemical element is the main component of human bones and teeth?',
        'Calcium',
        'Iron',
        'Sodium',
        'Magnesium',
        1),
       ('Which organ in the human body is responsible for filtering blood and producing urine?',
        'Heart',
        'Liver',
        'Kidneys',
        'Spleen',
        3),
       ('In what year was the first official Olympics held in modern times?',
        '1892',
        '1900',
        '1924',
        '1936',
        2),
       ('Which planet in the solar system has the largest diameter?',
        'Mercury',
        'Venus',
        'Earth',
        'Jupiter',
        4),
       ('What chemical element is used to fill balloons and airships?',
        'Hydrogen',
        'Oxygen',
        'Helium',
        'Neon',
        3),
       ('In what year did the Renaissance (Renaissance) begin?',
        '1300',
        '1453',
        '1500',
        '1600',
        3),
       ('What chemical element is used in the manufacture of batteries?',
        'Lead',
        'Copper',
        'Aluminum',
        'Lithium',
        4),
       ('What type of radiation allows X-ray examinations?',
        'Ultrasound',
        'Radioactivity',
        'Infrared',
        'X-ray',
        4),
       ('What chemical element is used to create rainbows in televisions and computer monitors?',
        'Helium',
        'Oxygen',
        'Hydrogen',
        'Neon',
        4),
       ('Which planet in the solar system is known as the “Blue Planet”?',
        'Venus',
        'Earth',
        'Uranus',
        'Neptune',
        2),
       ('In what year did the first man land on the moon?',
        '1961',
        '1969',
        '1975',
        '1983',
        2),
       ('Which actor portrayed James Bond in a record seven movies?',
        'Bradd Pitt',
        'Daniel Craig',
        'Pierce Brosnan',
        'Roger Moore',
        4),
       ('Filaria is caused by',
        'Bacteria',
        'Mosquito',
        'Protozoa',
        'Virus',
        2),
       ('Fathometer is used to measure',
        'Earthquakes',
        'Rainfall',
        'Ocean depth',
        'Sound intensity',
        3),
       ('In which year, did terrorists crash two planes into New York World Trade Centre?',
        '2000',
        '2001',
        '2002',
        '2003',
        2),
       ('In an adult human body, the total number of red blood cells is',
        '15 trillion',
        '20 trillion',
        '25 trillion',
        '30 trillion',
        4),
       ('In which season do we need more fat?',
        'Autumn',
        'Spring',
        'Winter',
        'Summer',
        3),
       ('How many teeth does an adult dog have?',
        '32',
        '34',
        '38',
        '42',
        4),
       ('How many times has Brazil won the World Cup?',
        '4',
        '2',
        '5',
        '1',
        3),
       ('How many players are there on each side of the Basketball game?',
        '4',
        '5',
        '6',
        '7',
        2),
       ('Hundred year war was between',
        'France and England',
        'Greek and Persian forces',
        'Civil War in England',
        'None of the above',
        1),
       ('Which animal is known to be the ‘Ship of the Desert”?',
        'Dog',
        'Camel',
        'Cat',
        'Snake',
        2),
       ('Who was the first person to walk on the moon?',
        'Yuri Gagarin',
        'Neil Armstrong',
        'John Glenn',
        'Buzz Aldrin',
        2),
       ('Which country was divided into two parts by the Wall?',
        'France',
        'Germany',
        'Austria',
        'Poland',
        2),
       ('Which city is the capital of Italy?',
        'Venice',
        'Florence',
        'Rome',
        'Milan',
        3),
       ('Which of these buildings is in India?',
        'Eiffel Tower',
        'Colosseum',
        'Taj Mahal',
        'Great Wall of China',
        3),
       ('In which country was the famous composer Wolfgang Amadeus Mozart born?',
        'Germany',
        'Austria',
        'Czech Republic',
        'Italy',
        2),
       ('Which of the following inventions is attributed to Thomas Edison?',
        'Bulb',
        'Telephone',
        'Computer',
        'Rocket',
        1),
       ('Which animal is a symbol of courage and bravery in Chinese culture?',
        'Leo',
        'Dragon',
        'Eagle',
        'Bear',
        2),
       ('Who invented the telegraph?',
        'Alexander Graham Bell',
        'Guglielmo Marconi',
        'Thomas Edison',
        'Samuel Morse',
        4),
       ('104.What animal is the symbol of China?',
        'Panda',
        'Elephant',
        'Tiger',
        'Leo',
        1),
       ('Which of these cities is located in Egypt?',
        'Athens',
        'Cairo',
        'Baghdad',
        'London',
        2),
       ('Which vitamin is often referred to as the “sunshine vitamin”?',
        'Vitamin A',
        'Vitamin B',
        'Vitamin C',
        'Vitamin D',
        4),
       ('What event led to the start of World War II?',
        'The fall of the Berlin Wall',
        'Attack on Pearl Harbor',
        'The signing of the Treaty of Versailles',
        'The capture of Crimea by Germany',
        2),
       ('What is the name of the longest river in Russia?',
        'Volga',
        'Lena',
        'Neva',
        'Amur',
        2),
       ('Who was the first President of the USA?',
        'George Washington',
        'John Adams',
        'Thomas Jefferson',
        'James Madison',
        1),
       ('Who is the founder of the modern theory of evolution?',
        'Charles Darwin',
        'Isaac Newton',
        'Albert Einstein',
        'Marie Curie',
        1),
       ('Which country is considered the birthplace of the Olympic Games?',
        'Greece',
        'Rome',
        'Egypt',
        'China',
        1),
       ('Who wrote the play “Romeo and Juliet”?',
        'William Shakespeare',
        'Alexander Pushkin',
        'Fyodor Dostoyevsky',
        'Victor Hugo',
        1),
       ('Which of these animals cannot jump?',
        'Cat',
        'Horse',
        'Snake',
        'Kangaroo',
        3),
       ('Which canal connects the Red and Mediterranean seas?',
        'Suez Canal',
        'Panama Canal',
        'Gotthard Tunnel',
        'Bosphorus Strait',
        1),
       ('What year did the Titanic sink in the Atlantic Ocean?',
        '1913',
        '1912',
        '1812',
        '1920',
        2),
       ('What social network used “stories” first?',
        'VKontakte',
        'Facebook',
        'Instagram',
        'Twitter',
        3),
       ('What game became popular due to the principle of “catch Pokemon in the real world”?',
        'Mario Kart Tour',
        'Clash of Clans',
        'Pokemon GO',
        'Candy Crush Saga',
        3),
       ('What device is used to view content in virtual reality?',
        'Smartphone',
        '3D glasses',
        'VR Headset',
        'Tablet',
        3),
       ('Which month is the shortest on the calendar?',
        'January',
        'February',
        'March',
        'December',
        1),
       ('Which city is the capital of Russia?',
        'St. Petersburg',
        'Kazan',
        'Sochi',
        'Moscow',
        4);


--sports qs
INSERT INTO sports_qs(question, option1, option2, option3, option4, correct_answer)
VALUES ('What sport is considered the most popular in the world?',
        'Football',
        'Tennis',
        'Golf',
        'Basketball',
        1),
       ('Which team won the last World Hockey Championship?',
        'Russia',
        'Canada',
        'United States',
        'Finland',
        2),
       ('What year is officially recognized as the beginning of the modern Olympic Games?',
        '1886',
        '1896',
        '1906',
        '1916',
        2),
       ('What material is used for weights in most bicycle races?',
        'Lead',
        'Glass',
        'Aluminum',
        'Concrete',
        1),
       ('What distance do marathon participants run?',
        '10 kilometres',
        '21 kilometres',
        '42,195 kilometres',
        '100 kilometres',
        3),
       ('In what country was boxer Muhammed Ali born?',
        'United States',
        'United Kingdom',
        'Canada',
        'Jamaica',
        1),
       ('What kind of sport is connected with the term “ring”?',
        'Figure skating',
        'Boxing',
        'Water polo',
        'Struggle',
        2),
       ('What ball is used in table tennis?',
        'Football',
        'Basketball',
        'Tennis',
        'Ping-pong',
        4),
       ('Which of the following sports does not include the use of a bicycle?',
        'Mountain skiing',
        'Triathlon',
        'Drift-tracking',
        'Road cycling',
        1),
       ('Which athlete won the largest number of gold medals at the Olympic Games?',
        'Michael Phelps',
        'Usain Bolt',
        'Maria Sharapova',
        'Yusuf Bolt',
        1),
       ('What colour ball is used in most snooker games?',
        'Green',
        'Blue',
        'Red',
        'Yellow:',
        3),
       ('In what year were the first modern Winter Olympic games held?',
        '1924',
        '1932',
        '1948',
        '1956',
        1),
       ('What game is called the “sport of kings”?',
        'Chess',
        'Go',
        'Bridge',
        'Tennis',
        1),
       ('What ball is used in basketball?',
        'Football',
        'Volleyball:',
        'Handball',
        'Basketball',
        4),
       ('In what year was the International Football Federation (FIFA) founded?',
        '1904',
        '1923',
        '1948',
        '1960',
        1),
       ('What is the place of chess player Magnus Carlsen in the list of the highest-paid sportsmen in the world?',
        'First',
        'Second',
        'Third',
        'Fifth',
        3),
       ('Which country won the most gold medals at the Summer Olympics?',
        'United States',
        'USSR',
        'China',
        'United Kingdom',
        1),
       ('In what country is the biggest tennis tournament “Wimbledon” taking place?',
        'United States',
        'United Kingdom',
        'France',
        'Australia',
        2),
       ('What sport is associated with the term “skating stadium”?',
        'Figure skating',
        'Short track',
        'Skating sport',
        'Hockey',
        3),
       ('What is the maximum number of players on the field at the same time in a football team?',
        '9',
        '10',
        '11',
        '12',
        3),
       ('In what kind of sport are the “Golden Ball” medals won?',
        'Hockey',
        'Football',
        'Baseball',
        'Basketball',
        2),
       ('What type of wrestling is represented at the Olympic Games?',
        'Greco-Roman struggle',
        'Jiu-jitsu',
        'Kickboxing',
        'Taekwondo',
        1),
       ('In what kind of sport are the “Golden Stanley Cup” medals won?',
        'Baseball',
        'American football',
        'Hockey',
        'Basketball',
        3),
       ('What is the distance run by the participants of the standard run of 100 meters?',
        '50 meters',
        '100 meters',
        '200 meters',
        '400 meters',
        2),
       ('In what country is the “Masters of Golf” tournament held?',
        'United States',
        'United Kingdom',
        'Australia',
        'Germany',
        1),
       ('Which sport includes the disciplines “biathlon” and “ski racing with obstacles”?',
        'Skis',
        'Biathlon',
        'Jumping with trampoline',
        'Skeleton',
        2),
       ('What type of wrestling includes actions on the stand and on the floor?',
        'Greco-Roman struggle',
        'Dzyudo:',
        'Sambo',
        'Jiu-jitsu',
        3),
       ('What is the maximum number of players on the field at the same time in a volleyball team?',
        '4',
        '5',
        '6',
        '7',
        3),
       ('What kind of sport includes the discipline “freestyle”?',
        'Swimming',
        'Skiing',
        'Figure skating',
        'Snowboarding',
        4),
       ('What game is considered the national sport of Japan?',
        'Tennis',
        'Golf',
        'Baseball',
        'Sumo:',
        4),
       ('Who is the record holder for the number of goals scored at one World Football Championship?',
        'Pele',
        'Miroslav Klose',
        'Just Fontaine',
        'Gerd Müller',
        3),
       ('Which country held the first official football match?',
        'England',
        'Brazil',
        'Germany',
        'Uruguay',
        4),
       ('Which club won the UEFA Champions League the most times?',
        'Real Madrid',
        'Barcelona',
        'Bayern Munich',
        'Manchester United',
        1),
       ('Which football player was recognized as the best player in the world according to FIFA in 2020?',
        'Lionel Messi',
        'Cristiano Ronaldo',
        'Neymar',
        'Kylian Mbappé',
        1),
       ('Which stadium is the largest by capacity in the world?',
        'Santiago Bernabeu',
        'Maracana',
        'Camp Nou',
        'Rungrado 1st of May Stadium',
        4),
       ('Who won the Golden Ball as the best football player in the world the largest number of times?',
        'Lionel Messi',
        'Cristiano Ronaldo',
        'Michel Platini',
        'Diego Maradona',
        1),
       ('Which football club became famous as “Right Side” in the 1970s?',
        'Liverpool',
        'Everton',
        'Manchester United',
        'Manchester City',
        1),
       ('Which football club won the UEFA Champions League in 2021?',
        'PSG',
        'Manchester City',
        'Bayern Munich',
        'Chelsea',
        4),
       ('Which football player is called “Korol Gola”?',
        'Diego Maradona',
        'Ferenc Puskas',
        'Pele',
        'Joseph Blatter',
        2),
       ('Which event is considered the most prestigious in the world of football?',
        'World Cup',
        'Confederations Cup',
        'Cup of America',
        'Championship of Europe',
        1),
       ('In what year did the first match of the World Football Championship take place?',
        '1926',
        '1930',
        '1934',
        '1938',
        2),
       ('Which country won the 2018 World Cup?',
        'France',
        'Argentina',
        'Germany',
        'Italy',
        1),
       ('Who is the best scorer in the history of the World Cup?',
        'Pele',
        'Gerd Müller',
        'Ronaldo',
        'Miroslav Klose',
        4),
       ('In what country was the first world football championship for women held?',
        'United States',
        'Norway',
        'Sweden',
        'China',
        1),
       ('Which football player is considered the best African player of all time?',
        'Didier Drogba',
        'George Uea',
        'Samuel Eto',
        'Yaya Touré',
        2),
       ('Which country organized the 2014 World Cup?',
        'Germany',
        'Brazil',
        'South Africa',
        'Russia:',
        2),
       ('Which club won the most UEFA Cup Leagues (now Europa League)?',
        'Seville',
        'Juventus',
        'Manchester United',
        'Inter Milan',
        1),
       ('Who was the coach of the German national team at the 2014 World Cup?',
        'Jose Mourinho',
        'Luis Felipe Scolari',
        'Joaquin Lev',
        'Josep Guardiola',
        3),
       ('Which club won the UEFA Confederations Cup in 2021?',
        'France',
        'Germany',
        'Belgium',
        'Portugal',
        1),
       ('Which football player is considered the best Argentine player of all time?',
        'Alfredo Di Stefano',
        'Diego Maradona',
        'Lionel Messi',
        'Gabriel Batistuta',
        3),
       ('Which club won the UEFA Champions League in 2020?',
        'Liverpool',
        'Real Madrid',
        'Bayern Munich',
        'Manchester City',
        3),
       ('Which football player got the nickname “Black Pearl”?',
        'Eusébio',
        'Pele',
        'Diego Maradona',
        'Georges Veilla',
        1),
       ('Which club won the UEFA Champions League in 2019?',
        'Liverpool',
        'Real Madrid',
        'Barcelona',
        'Juventus',
        1),
       ('Which player scored the fastest goal in football history?',
        'Cristiano Ronaldo',
        'Roberto Carlos',
        'David Beckham',
        'Jose Luis Chilevert',
        2),
       ('Which club won the FIFA Club World Cup in 2020?',
        'Bayern Munich',
        'Liverpool',
        'Real Madrid',
        'Flamengo',
        4),
       ('Which football player got the nickname “Fenomen”?',
        'Ronaldo',
        'Ronaldinho',
        'Кака:',
        'Pele',
        1),
       ('Which club won the American Cup in 2021?',
        'Brazil',
        'Argentina',
        'Uruguay',
        'Colombia',
        2),
       ('Which football player is called a “Black stallion”?',
        'Thierry Henry',
        'Eric Cantona',
        'Zinedine Zidane',
        'Didier Drogba',
        2),
       ('Which football player was named the best player of the 2018 World Cup?',
        'Luka Modric',
        'Antoine Griezmann',
        'Kylian Mbappé',
        'Ivan Rakitic',
        1),
       ('Which player won the Golden Ball in 1994?',
        'Jean-Pierre Papin',
        'Romario',
        'Paolo Maldini',
        'Roberto Baggio',
        2),
       ('Who is the NBA record holder for the number of scored points for his entire career?',
        'LeBron James',
        'Michael Jordan',
        'Karl Malone',
        'Kareem Abdul-Jabbar',
        1),
       ('In what team does Luka Doncic play?',
        'Los Angeles Lakers',
        'Golden State Warriors',
        'Dallas Mavericks',
        'Miami Heat',
        3),
       ('How many championship titles did Tim Duncan win with “The San Antonio Spurs”?',
        '2',
        '4',
        '5',
        '6',
        3),
       ('Who is the youngest player in NBA history to score 50 points in one game?',
        'LeBron James',
        'Kobe Bryant',
        'Devin Booker',
        'Carmelo Anthony',
        3),
       ('Which player is known under the nickname “Spider-Man”?',
        'Russell Westbrook',
        'Dwight Howard',
        'Chris Paul',
        'Paul George',
        2),
       ('Which country has won the most Olympic gold medals in men field hockey?',
        'India',
        'Australia',
        'Germany',
        'None of the above',
        1),
       ('In what team did Shaquille ONeal start his career?',
        'Orlando Magic',
        'Los Angeles Lakers',
        'Philadelphia Sixers',
        'Miami Heat',
        1),
       ('Which player wore jersey number 23 in “Chicago Bulls” before Michael Jordan?',
        'Scottie Pippen',
        'Dennis Rodman',
        'Jerry Sloan',
        'Elgin Baylor',
        3),
       ('Who was the first player in NBA history to score 100 points in one game?',
        'Wilt Chamberlain',
        'Kareem Abdul-Jabbar',
        'Shakil ONeil',
        'Hakeem Olajuwon',
        1),
       ('Which player got the nickname “Carmelo”?',
        'Carmelo Anthony',
        'Carmelo Anthony',
        'Anthony Carmelo',
        'Melo Carmelo',
        1),
       ('Which player spent most of his career with the Los Angeles Lakers and was known as “Magic”?',
        'Elgin Baylor',
        'James Ward',
        'Michael Cooper',
        'Magic Johnson',
        4),
       ('Which player acquired the nickname “Bron Bron”?',
        'Dwight Howard',
        'LeBron James',
        'Kobe Bryant',
        'Deandje Sproles',
        2),
       ('Which player is in the “double-double” club with the most double-doubles in NBA history?',
        'Jordan Bell',
        'Wilt Chamberlain',
        'Mark Ayton',
        'Russell Westbrook',
        2),
       ('Which player is considered the best defender in NBA history and got the nickname “Krabica”?',
        'Gary Peyton',
        'Tony Allen',
        'Michael Jordan',
        'Clyde Drexler',
        1),
       ('Which team won the largest number of NBA championships?',
        'Los Angeles Lakers',
        'Boston Celtics',
        'Chicago Bulls',
        'Miami Heat',
        2),
       ('Which player is known as the “Board Eater” and has the record for the number of rebounds in NBA history?',
        'Karl Malone',
        'Tim Duncan',
        'Dirk Nowitzki',
        'Dennis Rodman',
        4),
       ('Which player has been named the most valuable player (MVP) most often in NBA history?',
        'Michael Jordan',
        'Kareem Abdul-Jabbar',
        'LeBron James',
        'Magic Johnson',
        3),
       ('Which player is known by the nickname “Great Defender” and played for “Detroit Pistons”?',
        'Charles Barkley',
        'Isaiah Thomas',
        'George Gervin',
        'George Mikaen',
        2),
       ('Which player is the record holder for scored points for the entire history of the NBA?',
        'LeBron James',
        'Karl Malone',
        'Kareem Abdul-Jabbar',
        'Michael Jordan',
        3),
       ('Which team won the most NBA championships?',
        'Los Angeles Lakers',
        'Boston Celtics',
        'Chicago Bulls',
        'Golden State Warriors',
        1),
       ('Who is considered the best defender in NBA history?',
        'Michael Jordan',
        'Hakeem Olajuwon',
        'LeBron James',
        'Gary Payton',
        4),
       ('Which player is called “Rocket Man”?',
        'Michael Jordan',
        'Karl Malone',
        'Shakil ONeil',
        'Hakeem Olajuwon',
        2),
       ('Who was the first player to score 100 points in one NBA game?',
        'LeBron James',
        'Wilt Chamberlain',
        'Kareem Abdul-Jabbar',
        'Michael Jordan',
        2),
       ('Which coach won the most NBA championships?',
        'Gregg Popovich',
        'Phil Jackson',
        'Red Auerbach',
        'Pat Riley',
        2),
       ('Which team won 73 games at once in the NBA season, setting a record?',
        'Chicago Bulls',
        'Los Angeles Lakers',
        'Golden State Warriors',
        'Boston Celtics',
        3),
       ('Which player got the nicknames “Baron” and “Golden Hand”?',
        'Karl Malone',
        'Shakil ONeil',
        'Kareem Abdul-Jabbar',
        'LeBron James',
        1),
       ('Which player earned the nickname “Shaq” and was one of the dominant centres in NBA history?',
        'Gary Payton',
        'Wilt Chamberlain',
        'Shakil ONeil',
        'Tim Duncan',
        3),
       ('Which player is in second place for most Championship wins?',
        'Gary Payton',
        'Karl Malone',
        'Shakil ONeil',
        'Sam Jones',
        4),
       ('Which player is known by his nickname “The Big Fundamental” and was the famous centre of the team “San Antonio Spurs”?',
        'Karl Malone',
        'Wilt Chamberlain',
        'Tim Duncan',
        'David Robinson',
        3),
       ('Who is the youngest player to ever win the MVP award in NBA history?',
        'Karl Malone',
        'LeBron James',
        'Michael Jordan',
        'Dirik Rozan',
        2),
       ('Who is considered the leader in “hits” in the history of baseball?',
        'Babe Ruth',
        'Pete Rose',
        'Tai Cobb',
        'Lou Gehrig',
        2),
       ('Which team won the largest number of World Baseball Championships (World Series)?',
        'New York Yankees',
        'St. Louis Cardinals',
        'Boston Red Sox',
        'Los Angeles Dodgers',
        1),
       ('Who is the record holder for the number of home runs in the MLB season?',
        'Barry Bonds',
        'Mark McGwire',
        'Sammy Sosa',
        'Roger Maris',
        2),
       ('Who is the youngest player to ever play in MLB?',
        'Michael Truth',
        'Bob Feller',
        'Carl Hubbell',
        'Cal Ripken Jr',
        2),
       ('Which baseball player is known as the “Bronze Bible”?',
        'Babe Ruth',
        'Lou Gehrig',
        'Ted Williams',
        'Hank Aaron',
        3),
       ('Which player became the first African-American player in MLB?',
        'Willie Mays',
        'Jackie Robinson',
        'Larry Dobie',
        'Satchel Page',
        2),
       ('Which baseball player holds the record for the most hits in an MLB career?',
        'Babe Ruth',
        'Barry Bonds',
        'Alex Rodriguez',
        'Hank Aaron',
        4),
       ('In what year was Major League Baseball (MLB) created?',
        '1869',
        '1901',
        '1927',
        '1950',
        1),
       ('Which team won the most consecutive World Baseball Championships (World Series)?',
        'Oakland Ace',
        'Los Angeles Dodgers',
        'New York Yankees',
        'Cleveland Indians',
        2),
       ('Who is the youngest player to ever play in an MLB game?',
        'Trevor Hoffman',
        'Mike Trout',
        'Duane Underwood',
        'Bob Feller',
        4),
       ('Which baseball player holds the MLB MVP award record?',
        'Barry Bonds',
        'Michael Jordan',
        'Mike Truth',
        'Pete Rose',
        1),
       ('What team won the first World Baseball Championship in 1903?',
        'New York Giants',
        'Boston Red Sox',
        'Chicago Cubs',
        'Detroit Tigers',
        2),
       ('Who among the following baseball players is known as the “Bronze Horse”?',
        'Roberto Clemente',
        'Nolan Ryan',
        'George Brett',
        'Ted Williams',
        1),
       ('Which player took part in the most MLB All-Star Games?',
        'Pete Rose',
        'Carl Hubbell',
        'Cal Ripken Jr',
        'Willie Mays',
        3),
       ('Which baseball player is known by his nickname “Elephant” and served in the army during the Second World War?',
        'Lou Gehrig',
        'Ted Williams',
        'Larry Dobie',
        'Hank Aaron',
        2),
       ('Which player earned the nickname “Baseball Devil” and was a legend in baseball and American football?',
        'Dicky Magero',
        'Buster Powell',
        'Jim Thorpe',
        'Gordy Howe',
        3),
       ('Which player is known by his nickname “King of Baseball” and was a partner of “King of Records”?',
        'Tommy Lasorda',
        'Don Mattingly',
        'Manny Ramirez',
        'Ernest Bjordz',
        2),
       ('What team won the last World Series before the “Baby Ruth” era?',
        'Boston Red Sox',
        'Philadelphia Athletics',
        'Chicago White Sox',
        'New York Giants',
        2),
       ('Which baseball player is the leader in the number of goals scored in the history of the World Series?',
        'Pete Rose',
        'Babe Ruth',
        'Michael Jordan',
        'Manny Ramirez',
        2),
       ('Which baseball player became the first to surpass the mark of 60 goals scored in one MLB season?',
        'Babe Ruth',
        'Jimmy Fox',
        'Roger Maris',
        'Baby Ruth',
        1),
       ('Which baseball player has the record for the number of goals scored in an MLB season?',
        'Barry Bonds',
        'Sammy Sosa',
        'Mark McGwire',
        'Roger Maris',
        1),
       ('Which baseball player is known by his nickname “Milk” and was one of the greatest baseball players from Latin America?',
        'Manny Ramirez',
        'Roberto Alomar',
        'Fernando Valenzuela',
        'Vladimir Guerrero',
        4),
       ('Which baseball player received the nickname “Hitting Machine” and set the record for the number of goals scored in one MLB game?',
        'Mark McGwire',
        'Jimmy Fox',
        'Lou Gehrig',
        'Tai Cobb',
        2),
       ('Which baseball player is known as “Sea Wolf” and was one of the most charismatic players in the history of baseball?',
        'Baby Ruth',
        'Danny Murphy',
        'Harry Houdini',
        'Hank Aaron',
        2),
       ('Which baseball player earned the nickname “King of Chaos” and was known for his parties and informal style of play?',
        'Johnny Manzel',
        'Manny Ramirez',
        'Charlie Sheen',
        'Roberto Alomar',
        2),
       ('Which player acquired the nickname “B-Rider” and was known for his impressive moves on the bases?',
        'Brock Lesnar',
        'Dion Sanders',
        'Babe Ruth',
        'Mariano Rivera',
        2),
       ('Which baseball player earned the nickname “Hare” and was a legendary player among lefties?',
        'Lou Gehrig',
        'Randy Johnson',
        'Mike Schmitz',
        'Andrew Hard',
        2),
       ('Which baseball player is known by his nickname “The King of Swing” and is considered one of the greatest baseball players in history?',
        'Michael Jordan',
        'Tai Cobb',
        'Honus Wagner',
        'Babe Ruth',
        4),
       ('Which baseball player became the first to surpass the 3, 000 - hit mark in his MLB career?',
        'Tai Cobb',
        'Pete Rose',
        'Harry Houdini',
        'Hank Aaron',
        1),
       ('Which team won the first World Baseball Championship after the merger of the American and National Baseball Leagues?',
        'St. Louis Browns',
        'Philadelphia Phillies',
        'Boston Braves',
        'Chicago White Sox',
        1);


-- programming qs
INSERT INTO programming_qs (question, option1, option2, option3, option4, correct_answer)
VALUES ('During program development, software requirements specify',
        'How the program will accomplish the task',
        'What the task is that the program must perform',
        'How to divide the task into subtasks',
        'How to test the program when it is done',
        2),
       ('Of the following, if statements, which one correctly executes three instructions if the condition is true?',
        'If (x < 0) a = b * 2;
y = x;
z = a – y;
',
        '{ if (x < 0) a = b * 2;
y = x;
z = a – y;
}',
        'If{ (x < 0) a = b * 2;
y = x;
z = a – y ;
}',
        'If (x < 0) { a = b * 2;
y = x;
z = a – y;
}',
        4),
       ('Which of the sets of statements below will add 1 to x if x is positive and subtract 1 from x if x is negative but leave x alone if x is 0?',
        'If (x > 0) x++;
else x--;',
        'If (x > 0) x++; else if (x < 0) x--;',
        'If (x == 0) x = 0; else x++; x--;',
        'X++; x--;',
        2),
       ('Jim currently runs a car rental dealership and wishes to write a program that allows the user to enter the temperature of the location they plan to visit and then recommend a car based on the data.  Below is a summary of the program structure Jim is looking for.         Temp greater than 80 a Convertible should be selected.         Temp  greater than 60 and less than 80 an SUV should be selected         Temp less than 60 a truck should be selected.   Jim has no trouble writing the code if the temperate is greater than 80 but gets stuck when he arrives at the second line of code which reads Temp greater than 60 and less than 80 an SUV should be selected.  What type of operator is Jim needing to use within his code?',
        '&&',
        '| |',
        '!=',
        '==',
        1),
       ('_______ is the process of finding errors and fixing them within a program.',
        'Compiling',
        'Executing',
        'Debugging',
        'Scanning',
        3),
       ('Analyze the two “if statements” below and select which answer best summarizes each line of code.         string name1, name2; int guess, answer;   if (name1.equals(name2))         if (guess == answer)',
        'The first if statement will compare the numerical value of the two names entered to see if they are equal and the second if statement will also compare the numerical values to see if they are equal',
        'The first if statement will not work correctly due to string values being used, the second if statement will correctly compare the variables guess and answer',
        'The first if statement will compare the two string values to see if they are equal and the second will compare the two integer values to see if they are equal.',
        'The first if statement should read if (name1 == name2) in order to properly compare the values and the second if statement will compare the numerical values to see if they are equal.',
        3),
       ('Sal needs to execute a section of code ten times within a program. Compare the selection structures below and select which one meets the needs identified.',
        'If-Else',
        'For',
        'While',
        'If',
        2),
       ('Kevin has implemented a While loop within his Java program. Assess the code statement below and select which answer best summarizes the output Kevin will experience once the while statement is executed. int count = 1; while (count <=25) { System.out.println (count); Count = count –1; } System.out.println (“Done”);',
        'The while loop will execute 25 times and print the numbers 1 through 25 and finish with the printing of Done.',
        'The while loop will execute 25 times and print the numbers 25 down to 1 and finish with the printing of Done.',
        'The while statement will not function correctly due to a missing semicolon(;) after the statement while (count <=25)',
        'The while statement will execute by counting down from 1 until infinity and result in an infinite loop.',
        4),
       ('A loop that never ends is referred to as a(n)_________.',
        'While loop',
        'Infinite loop',
        'Recursive loop',
        ') for loop',
        2),
       ('Kim has just constructed her first for loop within the Java language.  Which of the following is not a required part of a for loop?',
        'Initialization',
        'Condition',
        'Variable',
        'Increment',
        3),
       ('Jay is considering adding a repetition statement within his Java programming final project. Jay is unsure of the number of times each loop needs to execute.  Analyze the conditional statements below and select which statement best fits the need identified by Jay within his programming.',
        'While loop',
        'If-Else',
        'For loop',
        'Switch statement',
        1),
       ('Which command will stop an infinite loop?',
        'Alt - C',
        'Shift - C',
        'Esc',
        'Ctrl - C',
        4),
       ('Score =Keyboard.readInt(); while (score !=  -1)         { System.out.println (“The score is” + score); score =Keyboard.readInt();         } USER INPUT = -1, predict what will happen after the user input is accepted into the java program.',
        'The while statement will continue to ask the user to enter a score and then print out the score that has been received.',
        'The while loop will execute an infinite number of times because the program statement can never be false',
        'The while statement will never print the statement “The score is” because the condition present within the while will be false on the first time through.',
        'The while statement will function until a value other than –1 is entered.',
        4),
       ('Analyze the following error that was received when Scott tried to compile his Java program named average. Average.java:14: else without if else ^ Which of the following could have resulted in the error being generated?',
        'Scott used an infinite loop within his program',
        'Scott placed a semicolon at the end of an If statement',
        'Scott used an incorrect looping structure',
        'Scott omitted a line of code below the If statement such as a System.out.pritnln or a Keybaord.readInt();',
        4),
       ('Which keyword is used to declare a constant variable in Java?',
        'Const',
        'Static',
        'Final',
        'Immutable',
        3),
       ('What is the primary purpose of the uper keyword in Java?',
        'To call methods of the parent class',
        'To declare static methods',
        'To override methods in the subclass',
        'To increase the visibility of methods',
        1),
       ('Which of these is not an access modifier in Java?',
        'Protected',
        'Public',
        'Private',
        'Package',
        4),
       ('What does the continue statement do in a loop?',
        'Terminates the loop',
        'Skips the current iteration and proceeds to the next one',
        'Pauses the loop execution',
        'None of the above',
        2),
       ('In object-oriented programming, what does the concept of inheritance allow you to do?',
        'Create a class based on another class',
        'Combine multiple classes into one',
        'Encrypt data within a class',
        'None of the above',
        1),
       ('What is the function of the throw keyword in Java?',
        'It explicitly passes control to another part of the program.',
        'It is used to declare a variable.',
        'It terminates the program immediately.',
        'It is used to signal the occurrence of an exception.',
        4),
       ('What is a data structure?',
        'A programming language',
        'A collection of algorithms',
        'A way to store and organize data',
        'A type of computer hardware',
        3),
       ('What are the disadvantages of arrays?',
        'Index value of an array can be negative',
        'Elements are sequentially accessed',
        'Data structure like queue or stack cannot be implemented',
        'There are chances of wastage of memory space if elements inserted in an array are lesser than the allocated size',
        4),
       ('Which data structure is used for implementing recursion?',
        'Stack',
        'Queue',
        'List',
        'Array',
        1),
       ('The data structure required to check whether an expression contains a balanced parenthesis is?',
        'Queue',
        'Stack',
        'Tree',
        'Array',
        2),
       ('Which of the following is not the application of stack?',
        'Data Transfer between two asynchronous process',
        'Compiler Syntax Analyzer',
        'Tracking of local variables at run time',
        'A parentheses balancing program',
        1),
       ('Which data structure is needed to convert infix notation to postfix notation?',
        'Tree',
        'Branch',
        'Stack',
        'Queue',
        3),
       ('What is the value of the postfix expression 6 3 2 4 + – *?',
        '
74',
        '-18
',
        '22
',
        '40
',
        2),
       ('What data structure would you mostly likely see in non recursive implementation of a recursive algorithm?',
        'Stack',
        'Linked List',
        'Tree',
        'Queue',
        1),
       ('Which of the following statement(s) about stack data structure is/are NOT correct?',
        'Top of the Stack always contain the new node',
        'Stack is the FIFO data structure',
        'Null link is present in the last node at the bottom of the stack',
        'Linked List are used for implementing Stacks',
        2),
       ('The data structure required for Breadth First Traversal on a graph is?',
        'Array',
        'Stack',
        'Tree',
        'Queue',
        4),
       ('The prefix form of A-B/ (C * D ^ E) is?',
        '-A/B*C^DE',
        '-A/BC*^DE',
        '-ABCD*^DE',
        '-/*^ACBDE',
        1),
       ('Which of the following points is/are not true about Linked List data structure when it is compared with an array?',
        'Random access is not allowed in a typical implementation of Linked Lists',
        'Access of elements in linked list takes less time than compared to arrays',
        'Arrays have better cache locality that can make them better in terms of performance',
        'It is easy to insert and delete elements in Linked List',
        2),
       ('Which data structure is based on the Last In First Out (LIFO) principle?',
        'Tree',
        'Linked List',
        'Stack',
        'Queue',
        3),
       ('Which of the following application makes use of a circular linked list?',
        'Recursive function calls',
        'Undo operation in a text editor',
        'Implement Hash Tables',
        'Allocating CPU to resources',
        4),
       ('What is a bit array?',
        'Data structure that compactly stores bits',
        'Data structure for representing arrays of records',
        'Array in which elements are not present in continuous locations',
        'An array in which most of the elements have the same value',
        1),
       ('Which of the following tree data structures is not a balanced binary tree?',
        'Splay tree',
        'B-tree',
        'AVL tree',
        'Red-black tree',
        2),
       ('Which of the following is not the type of queue?',
        'Priority queue',
        'Circular queue',
        'Single ended queue',
        'Ordinary queue',
        3),
       ('Which of the following data structures can be used for parentheses matching?',
        'n-ary tree',
        'queue',
        'priority queue',
        'tack',
        4),
       ('Which algorithm is used in the top tree data structure?',
        'Backtracking',
        'Divide and Conquer',
        'Branch',
        'Greedy',
        2),
       ('What is the need for a circular queue?',
        'easier computations',
        'implement LIFO principle in queues',
        'effective usage of memory',
        'to delete elements based on priority',
        3),
       ('Which of the following is the most widely used external memory data structure?',
        'B-tree',
        'Red-black tree',
        'AVL tree',
        'Both AVL tree and Red-black tree',
        1),
       ('Which of the following is also known as Rope data structure?',
        'Linked List',
        'Array',
        'String',
        'Cord',
        4),
       ('Which of the following data structure can provide efficient searching of the elements?',
        'binary search tree',
        'unordered lists',
        '2-3 tree',
        'treap',
        3),
       ('What is an AVL tree?',
        'a tree which is unbalanced and is a height balanced tree',
        'a tree which is balanced and is a height balanced tree',
        'a tree with atmost 3 children',
        'a tree with three children',
        2),
       ('What is the time complexity for searching a key or integer in Van Emde Boas data structure?',
        'O (M!)',
        'O (log M!)',
        'O (log (log M))',
        'O (M2)',
        3),
       ('The optimal data structure used to solve Tower of Hanoi is _________',
        'Tree',
        'Heap',
        'Priority queue',
        'Stack',
        4),
       ('What is the use of the bin data structure?',
        'to have efficient traversal',
        'to have efficient region query',
        'to have efficient deletion',
        'to have efficient insertion',
        2),
       ('Which is the most appropriate data structure for reversing a word?',
        'tack',
        'queue',
        'graph',
        'tree',
        1),
       ('Which of the following is the simplest data structure that supports range searching?',
        'AA-trees',
        'K-d trees',
        'Heaps',
        'binary search trees',
        2),
       ('What is the advantage of a hash table as a data structure?',
        'easy to implement',
        'faster access of data',
        'exhibit good locality of reference',
        'very efficient for less number of entries',
        2),
       ('Which type of data structure is a ternary heap?',
        'Hash',
        'Array',
        'Priority Stack',
        'Priority Queue',
        4),
       ('What is a dequeue?',
        'A queue implemented with both singly and doubly linked lists',
        'A queue with insert/delete defined for front side of the queue',
        'A queue with insert/delete defined for both front and rear ends of the queue',
        'A queue implemented with a doubly linked list',
        3),
       ('A data structure in which elements can be inserted or deleted at/from both ends but not in the middle is?',
        'Priority queue',
        'Dequeue',
        'Circular queue',
        'Queue',
        2),
       ('In simple chaining, what data structure is appropriate?',
        'Doubly linked list',
        'Circular linked list',
        'Singly linked list',
        'Binary trees',
        1),
       ('Who developed Python Programming Language?',
        'Wick van Rossum',
        'Rasmus Lerdorf',
        'Guido van Rossum',
        'Niene Stom',
        3),
       ('Which type of Programming does Python support?',
        'object-oriented programming',
        'tructured programming',
        'functional programming',
        'all of the mentioned',
        4),
       ('Is Python case sensitive when dealing with identifiers?',
        'no',
        'yes',
        'machine dependent',
        'none of the mentioned',
        2),
       ('Which of the following is the correct extension of the Python file?',
        '.python',
        '.pl',
        '.py',
        '.p',
        3),
       ('Is Python code compiled or interpreted?',
        'Python code is both compiled and interpreted',
        'Python code is neither compiled nor interpreted',
        'Python code is only compiled',
        'Python code is only interpreted',
        1),
       ('All keywords in Python are in _________',
        'Capitalized',
        'lower case',
        'UPPER CASE',
        'None of the mentioned',
        4),
       ('Which of the following is used to define a block of code in Python language?',
        'Indentation',
        'Key',
        'Brackets',
        'All of the mentioned',
        1),
       ('Which keyword is used for function in Python language?',
        'Function',
        'def',
        'Fun',
        'Define',
        2),
       ('Which of the following character is used to give single-line comments in Python?',
        '//',
        '#',
        '!',
        '/*',
        2),
       ('Which of the following functions can help us to find the version of python that we are currently working on?',
        'ys.version(1)',
        'ys.version(0)',
        'ys.version()',
        'ys.version',
        4),
       ('Python supports the creation of anonymous functions at runtime, using a construct called __________',
        'pi',
        'anonymous',
        'lambda',
        'none of the mentioned',
        3),
       ('What is the order of precedence in python?',
        'Exponential, Parentheses, Multiplication, Division, Addition, Subtraction',
        'Exponential, Parentheses, Division, Multiplication, Addition, Subtraction',
        'Parentheses, Exponential, Multiplication, Division, Subtraction, Addition',
        'Parentheses, Exponential, Multiplication, Division, Addition, Subtraction',
        4),
       ('What does pip stand for python?',
        'Pip Installs Python',
        'Pip Installs Packages',
        'Preferred Installer Program',
        'All of the mentioned',
        3),
       ('Which of the following is true for variable names in Python?',
        'underscore and ampersand are the only two special characters allowed',
        'unlimited length',
        'all private members must have leading and trailing underscores',
        'none of the mentioned',
        2),
       ('Which of the following is the truncation division operator in Python?',
        '|',
        '//',
        '/',
        '%',
        2),
       ('Which of the following functions is a built-in function in python?',
        'factorial()',
        'print()',
        'eed() ',
        'qrt()',
        2),
       ('Which of the following is the use of id() function in python?',
        'Every object doesn’t have a unique id',
        'Id returns the identity of the object',
        'All of the mentioned',
        'None of the mentioned',
        2),
       ('Which of the following is not a core data type in Python programming?',
        'Tuples',
        'Lists',
        'Class',
        'Dictionary',
        3),
       ('Which of these is the definition for packages in Python?',
        'A set of main modules',
        'A folder of python modules',
        'A number of files containing Python definitions and statements',
        'A set of programs making use of Python modules',
        2),
       ('What is the order of namespaces in which Python looks for an identifier?',
        'Python first searches the built-in namespace, then the global namespace and finally the local namespace',
        'Python first searches the built-in namespace, then the local namespace and finally the global namespace',
        'Python first searches the local namespace, then the global namespace and finally the built-in namespace',
        'Python first searches the global namespace, then the local namespace and finally the built-in namespace',
        3),
       ('Which one of the following is not a keyword in Python language?',
        'pass',
        'eval',
        'assert',
        'nonlocal',
        2),
       ('Which module in the python standard library parses options received from the command line?',
        'getarg',
        'getopt',
        'main',
        'os',
        2),
       ('What arithmetic operators cannot be used with strings in Python?',
        '*',
        '–',
        '+',
        'All of the mentioned',
        2),
       ('Which of the following statements is used to create an empty set in Python?',
        '( )',
        '[ ]',
        '{ }',
        'et()',
        4),
       ('To add a new element to a list we use which Python command?',
        'list1.addEnd(5)',
        'list1.addLast(5)',
        'list1.append(5)',
        'list1.add(5)',
        3),
       ('Which one of the following is the use of function in python?',
        'Functions don’t provide better modularity for your application',
        'you can’t also create your own functions',
        'Functions are reusable pieces of programs',
        'All of the mentioned',
        3),
       ('What is the maximum possible length of an identifier in Python?',
        '79 characters',
        '31 characters',
        '63 characters',
        'none of the mentioned',
        4),
       ('What are the two main types of functions in Python?',
        'System function',
        'Custom function',
        'Built-in function & User defined function',
        'User function',
        3),
       ('Which of the following is a Python tuple?',
        '{1, 2, 3}',
        '{}',
        '[1, 2, 3]',
        '(1, 2, 3)',
        4),
       ('Which of the following is a feature of Python DocString?',
        'In Python all functions should have a docstring',
        'Docstrings can be accessed by the __doc__ attribute on objects',
        'It provides a convenient way of associating documentation with Python modules, functions, classes, and methods',
        'All of the mentioned',
        4),
       ('What is output of print(math.pow(3, 2))?',
        '9.0',
        'None',
        '9',
        'None of the mentioned',
        1),
       ('Which of the following is the use of id() function in python?',
        'Every object in Python doesn’t have a unique id',
        'In Python Id function returns the identity of the object',
        'None of the mentioned',
        'All of the mentioned',
        2),
       ('The process of pickling in Python includes ____________',
        'conversion of a Python object hierarchy into byte stream',
        'conversion of a datatable into a list',
        'conversion of a byte stream into Python object hierarchy',
        'conversion of a list into a datatable',
        1),
       ('Who invented C++?',
        'Dennis Ritchie',
        'Ken Thompson',
        'Brian Kernighan',
        'Bjarne Stroustrup',
        4),
       ('What is C++?',
        'C++ is an object oriented programming language',
        'C++ is a procedural programming language',
        'C++ supports both procedural and object oriented programming language',
        'C++ is a functional programming language',
        3),
       ('Which of the following is the correct syntax of including a user defined header files in C++?',
        '#include [userdefined]',
        '#include “userdefined”',
        '#include <userdefined.h>',
        '#include <userdefined>',
        2),
       ('Which of the following is used for comments in C++?',
        '/* comment */',
        '// comment */',
        '// comment',
        'both // comment or /* comment */',
        4),
       ('Which of the following extension is used for user-defined header file in c++?',
        'hg',
        'cpp',
        'h',
        'hf',
        3),
       ('Which of the following is a correct identifier in C++?',
        'VAR_1234',
        '$var_name',
        '
7VARNAME',
        '
7var_name',
        1),
       ('Which of the following is not a type of Constructor in C++?',
        'Default constructor',
        'Parameterized constructor',
        'Copy constructor',
        'Friend constructor',
        4),
       ('Which of the following approach is used by C++?',
        'Left-right',
        'Right-left',
        'Bottom-up',
        'Top-down',
        3),
       ('What is virtual inheritance in C++?',
        'C++ technique to enhance multiple inheritance',
        'C++ technique to ensure that a private member of the base class can be accessed somehow',
        'C++ technique to avoid multiple inheritances of classes',
        'C++ technique to avoid multiple copies of the base class into children/derived class',
        4),
       ('Who invented Java Programming?',
        'Guido van Rossum',
        'James Gosling',
        'Dennis Ritchie',
        'Bjarne Stroustrup',
        2),
       ('Which statement is true about Java?',
        'Java is a sequence-dependent programming language',
        'Java is a code dependent programming language',
        'Java is a platform-dependent programming language',
        'Java is a platform-independent programming language',
        4),
       ('Which component is used to compile, debug and execute the java programs?',
        'JRE',
        'JIT',
        'JDK',
        'JVM',
        3),
       ('Which one of the following is not a Java feature?',
        'Object-oriented',
        'Use of pointers',
        'Portable',
        'Dynamic and Extensible',
        2),
       ('Which of these cannot be used for a variable name in Java?',
        'identifier & keyword',
        'identifier',
        'keyword',
        'none of the mentioned',
        3),
       ('What is the extension of java code files?',
        '.js',
        '.txt',
        '.class',
        '.java',
        4),
       ('Which environment variable is used to set the java path?',
        'MAVEN_Path',
        'JavaPATH',
        'JAVA',
        'JAVA_HOME',
        4),
       ('Which of the following is not an OOPS concept in Java?',
        'Polymorphism',
        'Inheritance',
        'Compilation',
        'Encapsulation',
        3),
       ('What is not the use of “this” keyword in Java?',
        'Referring to the instance variable when a local variable has the same name',
        'Passing itself to the method of the same class',
        'Passing itself to another method',
        'Calling another constructor in constructor chaining',
        2)