-- users
INSERT INTO users (username, password, email, score, country)
VALUES ('Melika', 'pass123@', 'melika@example.com', 0, 'Iran'),
       ('Moeein', 'pass123@', 'moeein@example.com', 0, 'Iran');
--quiz
INSERT INTO quiz (question, option1, option2, option3, option4, correct_answer)
VALUES ('In what year did the Great October Socialist Revolution take place?',
        '1917', '1923',
        '1914', '1920', 1),
       ('What is the largest lake in the world?',
        'Caspian Sea', 'Baikal',
        'Lake Superior', 'Ontario', 2),
       ('Which planet in the solar system is known as the “Red Planet”?',
        'Venus', 'Earth',
        'Mars', 'Jupiter', 3),
       ('Who wrote the novel “War and Peace”?',
        'Anton Chekhov', 'Fyodor Dostoevsky',
        'Leo Tolstoy', 'Ivan Turgenev', 3),
       ('What is the capital of Japan?',
        'Beijing', 'Tokyo',
        'Seoul', 'Bangkok', 2),
       ('Which river is the longest in the world?',
        'Amazon', 'Mississippi',
        'Nile', 'Yangtze', 3),
       ('What gas is used to extinguish fires?',
        'Oxygen', 'Nitrogen',
        'Carbon dioxide', 'Hydrogen', 2),
       ('What animal is the national symbol of Australia?',
        'Kangaroo', 'Koala',
        'Emu', 'Crocodile', 1),
       ('Which of the following planets is not a gas giant?',
        'Mars', 'Jupiter',
        'Saturn', 'Uranus', 1),
       ('What is the name of the process by which plants convert sunlight into energy?',
        'Respiration', 'Photosynthesis',
        'Oxidation', 'Evolution', 2),
       ('What chemical element is designated as “Hg”?',
        'Silver', 'Tin',
        'Copper', 'Mercury', 4),
       ('In what year was the first international modern Olympiad held?',
        '1896', '1900',
        '1912', '1924', 1),
       ('For which of these disciplines Nobel Prize is awarded?',
        'Physics, Chemistry', 'Physiology',
        'Medicine', 'All of the above', 4),
       ('Entomology is the science that studies:',
        'Behavior of human beings', 'Insects',
        'The origin and history of technical and scientific terms',
        'The formation of rocks', 2),
       ('Hitler''s party is known as:',
        'Labour Party', 'Nazi Party',
        'Ku-Klux-Klan', 'Democratic Party', 2),
       ('For which Galileo is famous?',
        'Developed the telescope', 'Discovered four satellites of Jupiter',
        'Found that the swinging motion of the pendulum results in consistent time measurement.',
        'All of the above', 4),
       ('When the First Afghan War took place in:',
        '1839', '1843',
        '1833', '1848', 1),
       ('Ecology deals with:',
        'Birds', 'Cell formation',
        'Relation between organisms and their environment',
        'Tissues', 3),
       ('Which is the largest island?',
        'New Guinea', 'Andaman Nicobar',
        'Greenland', 'Hawaii', 3),
       ('Which one is the hottest continent?',
        'Africa', 'South Asia',
        'North America', 'Australia', 1),
       ('What do Koalas usually eat?',
        'Bamboo', 'Eucalyptus',
        'Aloe Vera', 'Banana', 2),
       ('When the First Afghan War took place in:',
        'Brioche', 'Baguette',
        'White bread', 'Ciabatta', 2),
       ('What is the official currency of Japan?',
        'Won', 'Yuan',
        'Yen', 'Dollars', 3),
       ('What is the phobia of thunder and rain?',
        'Agoraphobia', 'Ombrophobia',
        'Acrophobia', 'Claustrophobia', 2),
       ('What does Carpe Diem mean in Latin?',
        'Enjoy the moment', 'Have no fear',
        'Sorry I blew it', 'Hello', 1),
       ('Which one of the following countries is not in Africa?',
        'Morocco', 'Yemen',
        'Sudan', 'Algeria', 2),
       ('What is considered the lung of the Earth?',
        'Amazon rainforest', 'The Mississippi River',
        'The Sahara', 'Everest', 1),
       ('Where does the Sushi come from?',
        'Japan', 'China',
        'America', 'South Korea', 1),
       ('In which century the Mona Lisa was painted?',
        '18th century', '15th century',
        '16th century', '14th century', 3),
       ('Who wrote the “Great Gatsby” novel?',
        'Leo Tolstoy', 'Hemingway',
        'Stephen King', 'F. Scott Fitzgerald', 4),
       ('Which is the richest country in the world?',
        'Qatar', 'Russia',
        'The USA', 'The UAE', 1),
       ('Which county is the biggest grower of coffee?',
        'Spain', 'India',
        'Ethiopia', 'Brazil', 4),
       ('How many bones are in the body of an adult human?',
        '330', '206',
        '250', '210', 2),
       ('When the humans use more facial muscles?',
        'While smiling', 'While frowning',
        'While sleeping', 'While talking', 2),
       ('Who wrote “Crime and Punishment”?',
        'Leo Tolstoy', 'Fyodor Dostoevsky',
        'Anton Chekhov', 'Ivan Turgenev', 2),
       ('In what year was the United Nations (UN) founded?',
        '1945', '1919',
        '1956', '1961', 1);
